[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "oikan"
version = "0.0.1"
description = "OIKAN: Optimized Interpretable Kolmogorov-Arnold Networks"
authors = [{name = "Arman Zhalgasbayev"}]
dependencies = [
    "torch",
    "numpy",
    "sympy",
    "scipy",
    "matplotlib"
]
