- name: Deploy GitHub Pages site
  uses: actions/deploy-pages@v4.0.5
  with:
    token: ${{ secrets.GITHUB_TOKEN }}
    path: docs
    timeout: 600000
    error_count: 10
    reporting_interval: 5000
    artifact_name: github-pages
    preview: false
