name: Publish to PyPI

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    environment: pypi
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install build dependencies
        run: pip install build

      - name: Build the package
        run: python -m build

      - name: Publish to PyPI using OpenID Connect
        uses: pypa/gh-action-pypi-publish@v1.7.0
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}